#include "embedding.h"
#include "../common_utils/json_portable.h"
#include <cstdlib>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <filesystem>
#include <chrono>
#include <atomic>

#ifdef _WIN32
#include <process.h>
#else
#include <unistd.h>
#endif

namespace
{
    long currentPid()
    {
#ifdef _WIN32
        return static_cast<long>(_getpid());
#else
        return static_cast<long>(getpid());
#endif
    }

    // Forward slashes avoid curl config-file backslash-escaping pitfalls on Windows paths.
    std::string toForwardSlashes(const std::string &path)
    {
        std::string out = path;
        for (char &c : out)
            if (c == '\\')
                c = '/';
        return out;
    }

    // Every path here is generated by us (pid + monotonic clock + counter), never derived
    // from user input, so it is safe to splice into a shell command or curl config file.
    std::string uniqueTempPath(const std::string &suffix)
    {
        static std::atomic<uint64_t> counter{0};
        uint64_t now = static_cast<uint64_t>(std::chrono::steady_clock::now().time_since_epoch().count());
        std::filesystem::path dir = std::filesystem::temp_directory_path();
        std::ostringstream name;
        name << "pxvb_embed_" << currentPid() << "_" << now << "_" << counter++ << suffix;
        return toForwardSlashes((dir / name.str()).string());
    }

    std::string readFile(const std::string &path)
    {
        std::ifstream file(path, std::ios::binary);
        std::ostringstream ss;
        ss << file.rdbuf();
        return ss.str();
    }
}

EmbeddingResult getEmbedding(const std::string &text, const std::string &model)
{
    EmbeddingResult result;

    if (text.empty())
    {
        result.error = "Cannot embed empty text.";
        return result;
    }

    const char *apiKey = std::getenv("OPENAI_API_KEY");
    if (apiKey == nullptr || std::string(apiKey).empty())
    {
        result.error = "OPENAI_API_KEY environment variable is not set.";
        return result;
    }

    Json::Value body;
    body["model"] = model;
    body["input"] = text;
    Json::StreamWriterBuilder bodyWriter;
    bodyWriter["indentation"] = "";
    std::string bodyStr = Json::writeString(bodyWriter, body);

    std::string bodyPath = uniqueTempPath(".json");
    std::string outPath = uniqueTempPath(".out.json");
    std::string configPath = uniqueTempPath(".curlcfg");

    {
        std::ofstream bodyFile(bodyPath, std::ios::binary | std::ios::trunc);
        bodyFile << bodyStr;
    }

    {
        std::ofstream cfgFile(configPath, std::ios::binary | std::ios::trunc);
        cfgFile << "url = https://api.openai.com/v1/embeddings\n";
        cfgFile << "request = POST\n";
        cfgFile << "header = Content-Type: application/json\n";
        cfgFile << "header = Authorization: Bearer " << apiKey << "\n";
        cfgFile << "data = @" << bodyPath << "\n";
        cfgFile << "output = " << outPath << "\n";
        cfgFile << "silent\n";
        cfgFile << "show-error\n";
    }

    std::string command = "curl -K \"" + configPath + "\"";
    int rc = std::system(command.c_str());

    std::string responseStr = readFile(outPath);

    std::remove(bodyPath.c_str());
    std::remove(outPath.c_str());
    std::remove(configPath.c_str());

    if (responseStr.empty())
    {
        result.error = "Failed to reach the embedding API (curl exit code " + std::to_string(rc) +
                        "). Is curl installed and is there network access?";
        return result;
    }

    Json::CharReaderBuilder readerBuilder;
    Json::Value root;
    std::string parseErrors;
    std::istringstream responseStream(responseStr);
    if (!Json::parseFromStream(readerBuilder, responseStream, &root, &parseErrors))
    {
        result.error = "Failed to parse embedding API response: " + parseErrors;
        return result;
    }

    if (root.isMember("error"))
    {
        result.error = "Embedding API error: " + root["error"].get("message", "unknown error").asString();
        return result;
    }

    if (!root.isMember("data") || !root["data"].isArray() || root["data"].empty())
    {
        result.error = "Embedding API response did not contain any embedding data.";
        return result;
    }

    const Json::Value &embeddingArr = root["data"][0]["embedding"];
    result.embedding.reserve(embeddingArr.size());
    for (const auto &v : embeddingArr)
        result.embedding.push_back(v.asFloat());

    result.success = true;
    return result;
}
